functional:
  - Пользователь должен иметь возможность играть в онлайн режиме.
  - Пользователь должен иметь возможность писать в чат зарегестрированным пользователям сайта.
  - Пользователь должен иметь возможность присылать приглашения другим пользователям.
  - Пользователь должен иметь возможность просматривать страницы профилей.
non-functional:
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен быть удобным на мобильном устройстве.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
implicit:
  - Сайт должен показывать пользователей онлайн.
  - Пользователь должен иметь возможность настроить игру под свой уровень знаний.
  - Пользователь должен иметь возможность видеть свои завершенные игры.
  - Пользователь должен иметь возможность зарегестрироваться разными способами. 
